### PR TITLE
[ObjC] Rewrite Obj-C workflow in Rust

### LINKED ISSUE #6779: It should be easier to add additional activities to Objective-C and shared cache workflows
**Version and Platform (required):**
- Binary Ninja Version: 5.1.7363-dev (acd6c39c)
- OS: macOS 15.4.1
- CPU Architecture: arm64

**Bug Description:**
There is currently no good way for a plug-in to add function activities to run in all Mach-O binaries (without Objective-C, with Objective-C, or that are loaded from the shared cache).

The `core.function.objectiveC` and `core.function.sharedCache` workflows both clone from `core.function.baseAnalysis` so they do not pick up any modifications a plug-in may make to `core.function.metaAnalysis`.

**Additional Information:**
There was some discussion [on Slack](https://binaryninja.slack.com/archives/C1E616ZSQ/p1745532210477839) about this. It sounds like the Objective-C and shared cache plug-ins could themselves modify `core.function.metaAnalysis` and make use of view type predicates to ensure their activities run only in their views.

Alternatively the workflows could instead clone `core.function.metaAnalysis`. It seems like there'd be an ordering issue there? That is, plug-ins would somehow need to ensure they're loaded and have modified `core.function.metaAnalysis` prior to the Objective-C or shared cache plug-ins creating their clones. I'm not sure there's any way to ensure that happens.

---

For now I work around this by explicitly registering activities in all three workflows. This requires that plug-ins declare an optional dependency on the `workflow_objc` and `sharedcache` plug-ins so that they are loaded and create their workflows before my plug-in is initialized. 

Sadly registering the activity multiple times while using automatic eligibility results in some log spew about the setting name:
```
[Default error] Setting: bdash.arm64e-pac already registered!
[Default error] Setting: bdash.arm64e-pac already registered!
```

### PR DESCRIPTION
**Pull request by bdash**
This is functionally equivalent to the previous workflow_objc, with the following changes:
1. It mutates the `core.function.metaAnalysis` workflow rather than registering a new named workflow. The activities now all check for the presence of the Objective-C metadata added by `ObjCProcessor` to determine whether they should do work, rather than relying on `MachoView` to override the function workflow when Objective-C metadata is present. This fixes https://github.com/Vector35/binaryninja-api/issues/6779.
2. The auto-inlining of `objc_msgSend` selector stub functions is performed in a separate activity from the processing of `objc_msgSend` call sites. The selector stub inlining activity is configured so that it does not run in `DSCView` as the shared cache needs different behavior for stub functions more generally that `SharedCacheWorkflow` already provides.
3. The way that types like `id` and `SEL` are referenced is fixed so that they show up as `id` rather than `objc_struct*`.

This also replaces the Objective-C portion of the shared cache's workflow, and incorporates several bug fixes that had been applied to it but not the standalone Objective-C workflow.

### CODE REVIEW

**Comment by bdash** [comment]
Having multiple different types of analysis of `objc_msgSend` call sites be in a single activity doesn't feel great, but the process of determining finding the individual call sites is complex enough that it'd be kinda gross to have to do it in multiple activities.

Perhaps there's some way I'm missing to communicate data between different activities that would allow me to have an "identify call sites" activity that call type adjustment and direct call rewriting activities could depend on so they could reuse data that it computes.

File: plugins/workflow_objc/src/metadata/global_state.rs [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+    NotLoaded,
+    Loaded(Option<SelectorImplementations>),
+}
+
+struct SelectorImplementations {
+    sel_ref_to_impl: HashMap<u64, Vec<u64>>,
+    sel_to_impl: HashMap<u64, Vec<u64>>,
+}
+
+// TODO: How do we ever clean up after these?
```
Comment (emesare) [inline plugins/workflow_objc/src/metadata/global_state.rs]: https://dev-rust.binary.ninja/binaryninja/trait.ObjectDestructor.html

Comment (bdash) [reply plugins/workflow_objc/src/metadata/global_state.rs]: Thanks! The C++ workflow had just been letting its equivalent maps grow indefinitely.
