### PR TITLE
[Mach-O] Handling for special library ordinals used in binding information

### LINKED ISSUE #6878: BIND_SPECIAL_DYLIB_SELF (and related special library ordinals) not handled correctly.
**Version and Platform (required):**
- Binary Ninja Version: 5.1.7418

**Bug Description:**
Chained fixups appear to parse improperly on a macOS x86_64 binary. 

Located at:
```
"/System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver"
```

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Load Binary
2. Open Log
3. Click address in an Objective-C error
4. Observe broken pointers.

[AppleIntelKBLGraphicsMTLDriver.zip](https://github.com/user-attachments/files/20442841/AppleIntelKBLGraphicsMTLDriver.zip)

### PR DESCRIPTION
**Pull request by 0cyn**
Adds handling for "BIND_SPECIAL_DYLIB_SELF" and related special library ordinals that influence symbol lookup when processing binding information. 

External Info: 
[dyld - Symbol Lookup](https://github.com/aosm/dyld/blob/master/src/ImageLoaderMachOCompressed.cpp#L796)

Resolves #6878

### CODE REVIEW

File: view/macho/machoview.h [hunk 1]
```diff
@@ -1375,6 +1382,13 @@ namespace BinaryNinja
 		uint32_t reserved;
 	};
 
+	struct BoundRelocation
+	{
+		BNRelocationInfo info;
+		std::string name;
+		int8_t ordinal;
```
Comment (bdash) [inline view/macho/machoview.h]: I think this needs to be a larger type:

```
mrowe@quicksilver:~$ rg -B 2 lib_ordinal $(xcrun --show-sdk-path)/usr
/Applications/Xcode-16.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach-o/fixup-chains.h
301-struct dyld_chained_import
302-{
303:    uint32_t    lib_ordinal :  8,   // -15 .. 240 (0xF1 .. 0xF0)
--
309-struct dyld_chained_import_addend
310-{
311:    uint32_t    lib_ordinal :  8,   // -15 .. 240 (0xF1 .. 0xF0)
--
318-struct dyld_chained_import_addend64
319-{
320:    uint64_t    lib_ordinal : 16,   // -15 .. 65520 (0xFFF1 .. 0xFFF0)
```
